# Generated by Django 4.1.7 on 2023-02-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WholesalerSFTPInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("host", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("port", models.SmallIntegerField()),
                ("import_directory", models.CharField(max_length=255, null=True)),
                ("export_directory", models.CharField(max_length=255, null=True)),
                ("is_wholesaler", models.BooleanField(default=True)),
            ],
        ),
    ]
